module.exports = {
    SERVER_ERR: "something went wrong",
    AUTH_HEADER_MISSING_ERR: "auth header is missing",
    AUTH_TOKEN_MISSING_ERR: "auth token is missing",
    JWT_DECODE_ERR: "incorrect token",
    USER_NOT_FOUND_ERR: "User not found",
    ACCESS_DENIED_ERR: "Access denied",
    SUCCESS: "success",
    ERROR: "error",
    INVALID_ARGUMENT: "invalid argument",
    PROBLEM_SENDING_OTP: "problem sending otp",
    NO_USER_FOUND: "no user found",
    USER_NOT_EXISTS: "user not exists",
    LOGIN_SUCCESS: "login sucessful",
    INCORRECT_OTP: "incorrect otp",
    LOGIN_REQUIRED: "you must be logged in",
    ERROR_UPDATING_USER: "error updating user",
    SUCCESS_UPDATE_USER: "user updated successfully",
    INVALID_CREDENTIALS: "invalid credentials",
    USER_NOT_VERIFIED: "user not verified",
    PERSONAL_DETAILS_NOT_FILLED: "personal details not filled"
}